name: linux
on:
  workflow_dispatch:
  push:
    tags:
      - 'nightly'

jobs:
  build:
    permissions:
      contents: write    # Required for creating/updating releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Increment version
        id: version
        run: |
          version=$(grep "define NIGHTLY" source/LeLib/data.cpp | awk '{ print $3 }')
          let version=${version}+1
          sed -i "s/define NIGHTLY .*/define NIGHTLY $version/" source/LeLib/data.cpp
          version=$(grep "define \(MAJOR\|FEATURE\|NIGHTLY\)" source/LeLib/data.cpp | awk '{ print $3 }' | xargs | sed 's/ /\./g')
          echo "::set-output name=TRSE_VERSION::${version}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qtbase5-dev \
            qt5-qmake \
            qtdeclarative5-dev \
            lz4 \
            python3 \
            nasm \
            vice

      - name: Build tools
        run: |
          mkdir tools
          pushd tools

          # vasm (Atari)
          wget --tries=3 https://www.irio.co.uk/div/vasm.tar.gz
          tar -xzf vasm.tar.gz
          pushd vasm
          make CPU=m68k SYNTAX=mot -j 4
          popd

          # exomizer
          wget --tries=3 https://bitbucket.org/magli143/exomizer/get/3.1.1.zip
          unzip 3.1.1.zip -d exomizer
          pushd exomizer/*/src
          make -j 4
          popd

          # Install VICE ROMs
          wget --tries=3 https://sourceforge.net/projects/vice-emu/files/releases/vice-3.5.tar.gz/download -O vice-3.5.tar.gz
          tar -xzf vice-3.5.tar.gz
          mkdir -p ~/.config/vice/
          cp -r vice-3.5/data/* ~/.config/vice/

          popd

      - name: Configure paths
        run: |
          exomizer=`ls ${PWD}/tools/exomizer/*/src/exomizer`
          sed -i "s,^vasmm =.*,vasmm = ${PWD}/tools/vasm/vasmm68k_mot," Publish/publish_linux/trse.ini
          sed -i "s,^exomizer =.*,exomizer = ${exomizer}," Publish/publish_linux/trse.ini
          c1541=$(which c1541)
          sed -i "s,^c1541 =.*,c1541 = ${c1541}," Publish/publish_linux/trse.ini
          x64=$(which x64)
          sed -i "s,^emulator =.*,emulator = ${x64}," Publish/publish_linux/trse.ini
          nasm=$(which nasm)
          sed -i "s,^nasm =.*,nasm = ${nasm}," Publish/publish_linux/trse.ini

      - name: Build TRSE
        run: |
          qmake PREFIX=/usr TRSE.pro
          make -j 4 -k

      - name: Build tar.gz
        run: cd Publish/publish_linux && ./publish nightly

      - name: Publish tar.gz
        uses: ColinPitrat/update-release@master
        with:
          release: nightly
          message: Nightly build
          body: TRSE ${{ steps.version.outputs.TRSE_VERSION }}
          files: Publish/publish_linux/trse_linux64.tar.gz
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}